name: deploy
on:
  workflow_dispatch:
  push:
    branches: [ main ]
jobs:
  deploy-document:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4

      - name: Compile document in LaTeX
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex

      - name: Move and rename document
        run: mkdir pages && mv main.pdf pages/paper.pdf

      - name: Deploy document to GitHub pages
        uses: JamesIves/github-pages-deploy-action@v4.4.3
        with:
          branch: gh-pages
          folder: pages
